apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmeteor-controller-manager
  namespace: kmeteor-system
  labels:
    app: kmeteor-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmeteor-controller-manager
  template:
    metadata:
      labels:
        app: kmeteor-controller-manager
    spec:
      serviceAccountName: kmeteor-controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/toamto/kmeteor:latest
          args:
            - --service-account-name=kmeteor-controller-manager
            - --leader-elect=false
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
