apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmeteor-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmeteor-manager-role
subjects:
  - kind: ServiceAccount
    name: kmeteor-controller-manager
    namespace: kmeteor-system
