//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChaosAction) DeepCopyInto(out *ChaosAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of this ChaosAction.
func (in *ChaosAction) DeepCopy() *ChaosAction {
	if in == nil {
		return nil
	}
	out := new(ChaosAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *KMeteor) DeepCopyInto(out *KMeteor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements the runtime.Object interface.
func (in *KMeteor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this KMeteor.
func (in *KMeteor) DeepCopy() *KMeteor {
	if in == nil {
		return nil
	}
	out := new(KMeteor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *KMeteorList) DeepCopyInto(out *KMeteorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KMeteor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements the runtime.Object interface.
func (in *KMeteorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this KMeteorList.
func (in *KMeteorList) DeepCopy() *KMeteorList {
	if in == nil {
		return nil
	}
	out := new(KMeteorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *KMeteorSpec) DeepCopyInto(out *KMeteorSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ChaosAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this KMeteorSpec.
func (in *KMeteorSpec) DeepCopy() *KMeteorSpec {
	if in == nil {
		return nil
	}
	out := new(KMeteorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *KMeteorStatus) DeepCopyInto(out *KMeteorStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.ScheduledJobs != nil {
		in, out := &in.ScheduledJobs, &out.ScheduledJobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of this KMeteorStatus.
func (in *KMeteorStatus) DeepCopy() *KMeteorStatus {
	if in == nil {
		return nil
	}
	out := new(KMeteorStatus)
	in.DeepCopyInto(out)
	return out
}
