apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kmeteor.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kmeteor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kmeteor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kmeteor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.operatorServiceAccount.name }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --job-service-account-name={{ .Values.jobServiceAccount.name }}
            - --leader-elect={{ .Values.leaderElection }}
            {{- if .Values.webUI.enabled }}
            - --web-ui-addr=:{{ .Values.webUI.port }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
            {{- if .Values.webUI.enabled }}
            - name: webui
              containerPort: {{ .Values.webUI.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
