{{- if .Values.jobRbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kmeteor.fullname" . }}-job
  labels:
    {{- include "kmeteor.labels" . | nindent 4 }}
rules:
  {{- if .Values.jobRbac.rules }}
  {{- toYaml .Values.jobRbac.rules | nindent 2 }}
  {{- else }}
  [] # no extra permissions — CronJobs only print "fired"
  {{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kmeteor.fullname" . }}-job
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kmeteor.labels" . | nindent 4 }}
rules:
  {{- if .Values.jobRbac.rules }}
  {{- toYaml .Values.jobRbac.rules | nindent 2 }}
  {{- else }}
  [] # no extra permissions — CronJobs only print "fired"
  {{- end }}
{{- end }}
